# Generated by Django 5.0.14 on 2025-05-01 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_review_book_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='book_id',
        ),
    ]
