# Generated by Django 5.0.14 on 2025-05-01 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_review_book_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='book_id',
            new_name='book',
        ),
    ]
