# Generated by Django 5.0.14 on 2025-05-01 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_authors_book_authors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Authors',
            new_name='Author',
        ),
    ]
